CREATE TABLE [dbo].[Video](
	[IdVideo] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [text] NOT NULL,
	[UrlVideo] [varchar](500) NOT NULL,
	[Tipo] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Video] ADD PRIMARY KEY CLUSTERED 
(
	[IdVideo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
